#!/bin/bash

PROGNAME=$(basename $0)

# Define default parameters
INSTALL_ONLY=false
LAYOUT_NAME="bepo_ebosi"
LAYOUT_DESC="French (Bepo, ergonomic, Dvorak way, ebosi, Etienne Boisseau-Sierra)"
LAYOUT_DEF_FILE="/usr/share/X11/xkb/symbols/fr"
LAYOUT_REF_FILE="/usr/share/X11/xkb/rules/evdev.xml"

usage() {
    echo "Install and load bepo_ebosi keyboard layout."
    echo
    echo "usage: $PROGNAME [-n name] [-d description] [-s path] [-r path] [-i] [-h]"
    echo
    echo "Options:"
    echo "  -h, --help            Show this help text"
    echo "  -n, --name            Set the layout name"
    echo "                            default: 'bepo_ebosi'"
    echo "  -d, --description     Set the layout description"
    echo "                            default: 'French (Bepo, ergonomic, Dvorak way, ebosi, Etienne Boisseau-Sierra)'"
    echo "  -s, --symbols-path    Set the path of the layout definition file"
    echo "                            default: '/usr/share/X11/xkb/symbols/fr'"
    echo "  -r, --reference-path  Set path of the layout reference file"
    echo "                            default: '/usr/share/X11/xkb/rules/evdev.xml'"
    echo "  -i, --install-only    Install the layout only (but does not load it)"
}

add_new_definition(){
    # Append custom bépo layout definition to the list of definitions,
    # while adapting the name and description on the fly

    cat fr_bepo_ebosi | sed "s/layout_name_placeholder/$LAYOUT_NAME/g;s/layout_description_placeholder/$LAYOUT_DESC/g" >> $LAYOUT_DEF_FILE
}

reference_new_definition(){
    # Add a reference to our new definition to the list of French ('fr') layouts

    xmlstarlet ed -L --subnode "xkbConfigRegistry/layoutList/layout[configItem[name[text()='fr']]]/variantList" --type elem -n newvariant $LAYOUT_REF_FILE
    xmlstarlet ed -L --subnode "xkbConfigRegistry/layoutList/layout[configItem[name[text()='fr']]]/variantList/newvariant" --type elem -n name -v "$LAYOUT_NAME" $LAYOUT_REF_FILE
    xmlstarlet ed -L --subnode "xkbConfigRegistry/layoutList/layout[configItem[name[text()='fr']]]/variantList/newvariant" --type elem -n description -v "$LAYOUT_DESC" $LAYOUT_REF_FILE
    xmlstarlet ed -L --rename "xkbConfigRegistry/layoutList/layout[configItem[name[text()='fr']]]/variantList/newvariant" -v variant $LAYOUT_REF_FILE
}

# Parse arguments

while [[ -n $1 ]]; do
    case $1 in
        -n | --name)            shift
                                LAYOUT_NAME=$1
                                ;;
        -d | --description)     shift
                                LAYOUT_DESC=$1
                                ;;
        -s | --symbols-path)    shift
                                LAYOUT_DEF_FILE=$1
                                ;;
        -r | --reference-path)  shift
                                LAYOUT_REF_FILE=$1
                                ;;
        -i | --install-only)    INSTALL_ONLY=true
                                ;;
        -h | --help)            usage
                                exit
                                ;;
        *)                      usage
                                exit 1
                                ;;
    esac
    shift
done

# Check that install can excecute

if ! type xmlstarlet > /dev/null; then
    # Test whether `xmlstarlet` is installed
    echo "Error: `xmlstarlet` not installed."
    exit 1
fi

for FILE in $LAYOUT_DESC_FILE $LAYOUT_REF_FILE
do
    if ! [ -w $FILE ]; then
        # Test whether user has write access on config files
        echo "Error: Permission denied on $FILE"
        echo "Try running as root."
        exit 1
    fi
done

# Install layout

# Add our new definition to the system
add_new_definition

# Make the new definition available to the system
reference_new_definition

if [ "$INSTALL_ONLY" = false ] ; then
    # Load the new keyboard layout
    setxkbmap -layout fr -variant $LAYOUT_NAME
fi
